basePath: /
definitions:
  domains.redisDTO:
    properties:
      Key:
        type: string
      Value:
        type: string
    type: object
  handler.MongoDTO:
    properties:
      Key:
        type: string
      Value:
        type: string
    type: object
host: localhost:3000
info:
  contact: {}
  description: Какая-то ебень
  title: Жопа
  version: "1.0"
paths:
  /createmongo:
    post:
      consumes:
      - application/json
      description: You can add data to mongo database via this endpoint
      operationId: create-mongo
      parameters:
      - description: Json for creating data
        in: body
        name: JsonExample
        required: true
        schema:
          $ref: '#/definitions/handler.MongoDTO'
      produces:
      - application/json
      responses: {}
      summary: Create mongo data
      tags:
      - Mongo
  /createredis:
    post:
      consumes:
      - application/json
      description: You can add data to redis database via this endpoint
      operationId: create-redis
      parameters:
      - description: Json for creating data
        in: body
        name: JsonExample
        required: true
        schema:
          $ref: '#/definitions/domains.redisDTO'
      produces:
      - application/json
      responses: {}
      summary: Create redis data
      tags:
      - Redis
  /deletemongo:
    delete:
      consumes:
      - application/json
      description: You can delete data from mongo database via this endpoint
      operationId: delete-mongo
      parameters:
      - description: Json for deleting data
        in: body
        name: JsonExample
        required: true
        schema:
          $ref: '#/definitions/handler.MongoDTO'
      produces:
      - application/json
      responses: {}
      summary: Delete mongo data
      tags:
      - Mongo
  /deleteredis:
    delete:
      consumes:
      - application/json
      description: You can delete data from redis database via this endpoint
      operationId: delete-redis
      parameters:
      - description: Json for deleting data
        in: body
        name: JsonExample
        required: true
        schema:
          $ref: '#/definitions/domains.redisDTO'
      produces:
      - application/json
      responses: {}
      summary: Delete redis data
      tags:
      - Redis
  /readmongo:
    get:
      description: You can read data from mongo database via this endpoint
      operationId: read-mongo
      produces:
      - application/json
      responses: {}
      summary: Read mongo data
      tags:
      - Mongo
  /readredis:
    get:
      consumes:
      - application/json
      description: You can read data from redis database via this endpoint
      operationId: read-redis
      parameters:
      - description: name search by query
        in: query
        name: key
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Read redis data
      tags:
      - Redis
  /updatemongo:
    put:
      consumes:
      - application/json
      description: You can update mongo data via this endpoint
      operationId: update-mongo
      parameters:
      - description: Json for updating data
        in: body
        name: JsonExample
        required: true
        schema:
          $ref: '#/definitions/handler.MongoDTO'
      produces:
      - application/json
      responses: {}
      summary: Update mongo data
      tags:
      - Mongo
  /updateredis:
    put:
      consumes:
      - application/json
      description: You can update redis data via this endpoint
      operationId: update-redis
      parameters:
      - description: Json for updating data
        in: body
        name: JsonExample
        required: true
        schema:
          $ref: '#/definitions/domains.redisDTO'
      produces:
      - application/json
      responses: {}
      summary: Update redis data
      tags:
      - Redis
swagger: "2.0"
